In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

Wind Direction (°)  LV ActivePower (kW)  Wind Speed (m/s)  \
0          259.994904           380.047790          5.311336   
1          268.641113           453.769196          5.672167   
2          272.564789           306.376587          5.216037   
3          271.258087           419.645904          5.659674   
4          265.674286           380.650696          5.577941   

   Theoretical_Power_Curve (KWh)  
0                     416.328908  
1                     519.917511  
2                     390.900016  
3                     516.127569  
4                     491.702972

In [4]:
df.isnull().sum

<bound method DataFrame.sum of        Wind Direction (°)  LV ActivePower (kW)  Wind Speed (m/s)  \
0                   False                False             False   
1                   False                False             False   
2                   False                False             False   
3                   False                False             False   
4                   False                False             False   
...                   ...                  ...               ...   
50525               False                False             False   
50526               False                False             False   
50527               False                False             False   
50528               False                False             False   
50529               False                False             False   

       Theoretical_Power_Curve (KWh)  
0                              False  
1                              False  
2                              Fals

In [5]:
x = df.iloc[:,0:3].values

In [6]:
x

array([[ 259.9949036 ,  380.0477905 ,    5.31133604],
       [ 268.6411133 ,  453.7691956 ,    5.67216682],
       [ 272.5647888 ,  306.3765869 ,    5.2160368 ],
       ...,
       [  84.74250031, 2201.106934  ,    8.43535805],
       [  84.2979126 , 2515.694092  ,    9.42136574],
       [  82.27462006, 2820.466064  ,    9.97933197]])

In [7]:
y = df.iloc[:,3:4].values

In [8]:
y

array([[ 416.3289078],
       [ 519.9175111],
       [ 390.9000158],
       ...,
       [1788.284755 ],
       [2418.382503 ],
       [2779.184096 ]])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
x.shape

(50530, 3)

In [12]:
x_train.shape

(40424, 3)

In [13]:
x_test.shape

(10106, 3)

In [14]:
y.shape

(50530, 1)

In [15]:
y_train.shape

(40424, 1)

In [16]:
y_test.shape

(10106, 1)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model=LinearRegression()

In [19]:
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
y_pred=model.predict(x_test)

In [21]:
y_pred

array([[ 873.79249176],
       [1779.68261449],
       [1843.49487151],
       ...,
       [ 949.14715813],
       [3401.54611663],
       [2501.2783914 ]])

In [22]:
y_test

array([[ 609.0814694],
       [1608.179354 ],
       [1650.739196 ],
       ...,
       [ 722.1880659],
       [3535.148673 ],
       [2972.398269 ]])

In [25]:
x_test

array([[  73.27832794,  576.6569824 ,    5.95249605],
       [  57.53897858, 1619.301025  ,    8.13491821],
       [ 254.491394  , 1876.581055  ,    8.20711517],
       ...,
       [ 124.689003  ,  667.2570801 ,    6.27890301],
       [  29.65011024, 3473.522949  ,   12.08922958],
       [  60.25027847, 2343.063965  ,   10.31402969]])

In [23]:
from sklearn.metrics import r2_score

In [24]:
r2_score(y_test,y_pred)

0.9390543482126902

In [28]:
rslt=model.predict([[  73.27832794,  576.6569824 ,    5.95249605],[270,4000,10.27]])

In [29]:
rslt

array([[ 873.79249147],
       [3312.37892943]])

In [33]:
import pickle
pickle.dump(model,open('wind.pkl','wb'))